# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = "#about"
  weight = 10

[[main]]
  name = "Experience"
  url = "#experience"
  weight = 15

[[main]]
  identifier = "Projects"
  name = "Projects"
  url = "#projects"
  weight = 20

  [[main]]
    parent = "Projects"
    name = "All"
    url = "#projects"
    weight = 1

  [[main]]
    parent = "Projects"
    name = "SnowC2 (2023-2025)"
    url = "project/snowc2"
    weight = 2

  [[main]]
    parent = "Projects"
    name = "PhD (2019-2022)"
    url = "project/phd"
    weight = 3

  [[main]]
    parent = "Projects"
    name = "Science et Climat"
    url = "project/science-et-climat"
    weight = 4

[[main]]
  name = "Posts"
  url = "#posts"
  weight = 30

[[main]]
  name = "Talks"
  url = "#talks"
  weight = 35

[[main]]
  name = "Publications"
  url = "#publications"
  weight = 40

[[main]]
  name = "Medias"
  url = "project/medias"
  weight = 41

[[main]]
  name = "Tutorials"
  url = "project/tutorials"
  weight = 42

[[main]]
  name = "CV"
  url = "files/CV_LALANDE_2023_v2.1.pdf"
  weight = 50

[[main]]
  name = "Contact"
  url = "#contact"
  weight = 60

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
